Importing Libaries and data

In [1]:
# import libraries
import pandas as pd
import numpy as np 
import os

In [2]:
path = r'/Users/thomaskimber/Desktop/Task 7'

In [3]:
# importing UFC data csv 
df = pd.read_csv(os.path.join(path, 'ufc_data.csv' ), index_col = False)

In [4]:
df.head()

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,B_avg_KD,B_avg_opp_KD,...,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,Adrian Yanez,Gustavo Lopez,Chris Tognoni,2021-03-20,"Las Vegas, Nevada, USA",Red,False,Bantamweight,0.000,0.0,...,0,1,0,0,Orthodox,170.18,177.80,135.0,31.0,27.0
1,Trevin Giles,Roman Dolidze,Herb Dean,2021-03-20,"Las Vegas, Nevada, USA",Red,False,Middleweight,0.500,0.0,...,0,3,0,0,Orthodox,182.88,187.96,185.0,32.0,28.0
2,Tai Tuivasa,Harry Hunsucker,Herb Dean,2021-03-20,"Las Vegas, Nevada, USA",Red,False,Heavyweight,NaN,NaN,...,1,3,0,0,Southpaw,187.96,190.50,264.0,32.0,28.0
3,Cheyanne Buys,Montserrat Conejo,Mark Smith,2021-03-20,"Las Vegas, Nevada, USA",Blue,False,WomenStrawweight,NaN,NaN,...,0,0,0,0,Switch,160.02,160.02,115.0,28.0,25.0
4,Marion Reneau,Macy Chiasson,Mark Smith,2021-03-20,"Las Vegas, Nevada, USA",Blue,False,WomenBantamweight,0.125,0.0,...,1,2,2,0,Orthodox,167.64,172.72,135.0,29.0,43.0

In [5]:
df.describe()

,B_avg_KD,B_avg_opp_KD,B_avg_SIG_STR_pct,B_avg_opp_SIG_STR_pct,B_avg_TD_pct,B_avg_opp_TD_pct,B_avg_SUB_ATT,B_avg_opp_SUB_ATT,B_avg_REV,B_avg_opp_REV,...,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
count,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.00000,4585.000000,...,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6008.000000,5606.000000,6010.000000,5840.000000,5949.000000
mean,0.247476,0.176818,0.453310,0.434290,0.292650,0.268742,0.478884,0.409276,0.15673,0.141306,...,0.306886,1.251331,1.297572,0.796241,0.069195,178.991788,183.562347,170.686356,29.293151,29.598252
std,0.378509,0.324633,0.130458,0.132618,0.273628,0.267178,0.724229,0.653826,0.34199,0.322623,...,0.619485,1.681376,1.859955,1.355801,0.273980,8.812985,10.585313,35.724626,4.063297,4.167755
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,152.400000,152.400000,115.000000,18.000000,19.000000
25%,0.000000,0.000000,0.376489,0.351045,0.031250,0.033203,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,172.720000,177.800000,145.000000,26.000000,27.000000
50%,0.015625,0.000000,0.450000,0.427500,0.250000,0.200000,0.148468,0.098389,0.00000,0.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,180.340000,182.880000,170.000000,29.000000,29.000000
75%,0.500000,0.250000,0.527500,0.510000,0.500000,0.422812,0.750000,0.531250,0.12500,0.125000,...,0.000000,2.000000,2.000000,1.000000,0.000000,185.420000,190.500000,185.000000,32.000000,32.000000
max,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,8.000000,7.000000,4.00000,3.000000,...,5.000000,10.000000,11.000000,13.000000,2.000000,210.820000,213.360000,345.000000,51.000000,47.000000

In [6]:
df.info

<bound method DataFrame.info of           R_fighter           B_fighter        Referee        date  \
0      Adrian Yanez       Gustavo Lopez  Chris Tognoni  2021-03-20
1      Trevin Giles       Roman Dolidze      Herb Dean  2021-03-20
2       Tai Tuivasa     Harry Hunsucker      Herb Dean  2021-03-20
3     Cheyanne Buys   Montserrat Conejo     Mark Smith  2021-03-20
4     Marion Reneau       Macy Chiasson     Mark Smith  2021-03-20
...             ...                 ...            ...         ...
6007  Remco Pardoel  Alberta Cerra Leon  John McCarthy  1994-03-11
6008   Orlando Wiet    Robert Lucarelli  John McCarthy  1994-03-11
6009  Johnny Rhodes       David Levicki  John McCarthy  1994-03-11
6010  Patrick Smith          Ray Wizard  John McCarthy  1994-03-11
6011   Scott Morris      Sean Daugherty  John McCarthy  1994-03-11

                    location Winner  title_bout       weight_class  B_avg_KD  \
0     Las Vegas, Nevada, USA    Red       False       Bantamweight     0.000
1     Las Vegas, Nevada, USA    Red       False       Middleweight     0.500
2     Las Vegas, Nevada, USA    Red       False        Heavyweight       NaN
3     Las Vegas, Nevada, USA   Blue       False   WomenStrawweight       NaN
4     Las Vegas, Nevada, USA   Blue       False  WomenBantamweight     0.125
...                      ...    ...         ...                ...       ...
6007   Denver, Colorado, USA    Red       False         OpenWeight       NaN
6008   Denver, Colorado, USA    Red       False         OpenWeight       NaN
6009   Denver, Colorado, USA    Red       False         OpenWeight       NaN
6010   Denver, Colorado, USA    Red       False         OpenWeight       NaN
6011   Denver, Colorado, USA    Red       False         OpenWeight       NaN

      B_avg_opp_KD  ...  R_win_by_Decision_Unanimous  R_win_by_KO/TKO  \
0              0.0  ...                            0                1
1              0.0  ...                            0                3
2              NaN  ...                            1                3
3              NaN  ...                            0                0
4              0.0  ...                            1                2
...            ...  ...                          ...              ...
6007           NaN  ...                            0                0
6008           NaN  ...                            0                0
6009           NaN  ...                            0                0
6010           NaN  ...                            0                0
6011           NaN  ...                            0                0

      R_win_by_Submission  R_win_by_TKO_Doctor_Stoppage  R_Stance  \
0                       0                             0  Orthodox
1                       0                             0  Orthodox
2                       0                             0  Southpaw
3                       0                             0    Switch
4                       2                             0  Orthodox
...                   ...                           ...       ...
6007                    0                             0  Southpaw
6008                    0                             0  Southpaw
6009                    0                             0  Orthodox
6010                    0                             0  Orthodox
6011                    0                             0  Orthodox

      R_Height_cms  R_Reach_cms  R_Weight_lbs  B_age  R_age
0           170.18       177.80         135.0   31.0   27.0
1           182.88       187.96         185.0   32.0   28.0
2           187.96       190.50         264.0   32.0   28.0
3           160.02       160.02         115.0   28.0   25.0
4           167.64       172.72         135.0   29.0   43.0
...            ...          ...           ...    ...    ...
6007        190.50          NaN         260.0    NaN    NaN
6008        177.80          NaN         170.0    NaN    NaN
6009        182.88          NaN         210.0    NaN    NaN
6010        187.96          NaN         225.0    NaN   30.0
6011        177.80          NaN         210.0   18.0    NaN

[6012 rows x 144 columns]>

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import os

In [8]:
matplotlib.__version__

'3.10.0'